name: stock_calculator
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_slider_drawer:
  lottie:
  shared_preferences:
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.1.14
  provider: ^6.1.1





  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: Figtree-Regular
      fonts:
        - asset: assets/fonts/Figtree-Regular.ttf

    - family: Figtree-Medium
      fonts:
        - asset: assets/fonts/Figtree-Medium.ttf

    - family: Figtree-Bold
      fonts:
        - asset: assets/fonts/Figtree-Bold.ttf

    - family: Figtree-SemiBold
      fonts:
        - asset: assets/fonts/Figtree-SemiBold.ttf
  assets:
    - lottie/
    - assets/fonts/
    - assets/icons/
    - assets/images/

