import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'setting': 'SETTINGS',
          'premium': 'Don’t miss out on exclusive features Tap to upgrade!',
          'language': 'Language',
          'yourPLan': 'Your Plan',
          'voice': 'Voice',
          'about': 'About',
          'rateUs': 'Rate Us',
          'shareWithF': 'Share with Friends',
          'terms': 'Terms of Use',
          'privacy': 'Privacy policy',
          'poweredBy': 'powered By',
          'history': 'HISTORY',
          'noData': 'Not data  found',
          'doYouDelete': 'Do to want to Delete ?',
          'areYouConfirm': 'Are you confirm',
          'confirm': 'Confirm',
          'cancel': 'Cancel',
          'restore': 'Restore',
          'premiumAdvanced': 'Advanced: Full unlimited access for complex tasks and management.',
          'premiumSub1': 'Unlimited request (per day: ∞)',
          'premiumSub2': 'Advanced AI Model(Turbo)',
          'premiumSub3': 'AI remembers chat history',
          'premiumSub4': 'AI Art Generator (Per day: ∞)',
          'premiumSub5': 'Ads free experience',
          'month': 'Month',
          'week': 'Week',
          'perWeek': 'per week',
          'perMonth': 'per month',
          'perYear': 'per year',
          'daysFree': '3 DAYS FREE',
          'me': 'ME',
          'askNewQuestion': 'Ask new question',
          'copy': 'Copy',
          'historyEmpty': 'History Is Empty',
          'pleaseEnterText': 'Please Enter Text',
          'continueChat': 'Continue To Chat',
          'startTrail': 'Start Free Trial And Plan',
          'askSomething': 'Ask Something',
          'premiumPrice1': 'INR 183.88/week',
          'premiumPrice2': 'INR 399.00/week',
          'premiumPrice3': 'INR 95.87/week',
          'voiceIsOff': 'Voice Is Off',
          'offer1': '1 Month',
          'offer2': '1 Week',
          'offer3': '1 Year',
          'imageGeneration': 'Image Generation',
          'imageSize': 'Image size',
          'imagePreview': 'Image Preview',
          'share': 'Share',
          'save': 'Save',
          'dark': 'Dark',
          'voiceIsOn': 'Voice On',
          'year': 'Year',
          'alreadyPremium': 'Already You are Premium',
          'buyPremium': 'Buy Premium',
          'termsIn': 'Terms',
          'privacyIn': 'Privacy',
          'autoRenewable': 'Auto-renewable, cancel anytime',
          'popular': 'Popular',
          'bestValue': 'Best Value',
          'oneYearPlan': 'Start 1 Year Plan',
          'oneMonthPlan': 'Start 1 Month Plan',
          'oneWeekPlan': 'Start 1 Week Plan',
          'getOlaPurchase': 'You get a old Purchase item',
          'notPurchaseBefore': 'You have not purchase anything before',
          'purchaseDone': 'Purchase Done',
          'failedFetch': 'Failed Fetch',
          'unlockFeature': 'Unlock feature',
          'proVersion': 'Pro version',
          'removeAds': 'Unlock all feature and remove ads.',
          'watchAds': 'Watch ads',
          'requests': 'watch an ad to unlock 1 more requests',
          'shareText':
              '''I share EduChat, an educational app with Artificial Intelligence, helps you in everything, download it here: 
https://play.google.com/store/apps/details?id=com.educhat.chatai''',
        },
        'gu_GU': {
          'setting': 'સેટિંગ',
          'language': 'ભાષા',
          'yourPLan': 'Tu plan',
          'voice': 'Voz',
          'about': 'About',
          'rateUs': 'Acerca de',
          'shareWithF': 'Compartir conamigos',
          'terms': 'Condiciones de uso',
          'privacy': 'Política de privacidad',
          'poweredBy': 'energizado por',
          'history': 'HISTORIA',
          'noData': 'No se encontraron datos',
          'doYouDelete': '¿Quieres eliminar?',
          'areYouConfirm': '¿Estás confirmando',
          'confirm': 'Confirmar',
          'cancel': 'Cancelar',
          'restore': 'Restaurar',
          'premiumAdvanced': 'Avanzado: acceso completo e ilimitado para tareas y gestión complejas.',
          'premiumSub1': 'Solicitud ilimitada (por día: ∞)',
          'premiumSub2': 'Modelo AI avanzado (Turbo)',
          'premiumSub3': 'AI recuerda el historial de chat',
          'premiumSub4': 'Generador de arte AI (Por día: ∞)',
          'premiumSub5': 'Experiencia sin anuncios',
          'month': 'Mes',
          'week': 'Semana',
          'perWeek': 'por semana',
          'perMonth': 'por mes',
          'perYear': 'por año',
          'daysFree': '3 DÍAS GRATIS',
          'me': 'A MÍ',
          'askNewQuestion': 'Haz una nueva pregunta',
          'copy': 'Copiar',
          'historyEmpty': 'La historia está vacía',
          'pleaseEnterText': 'Por favor ingrese texto',
          'continueChat': 'Continuar al chat',
          'startTrail': 'Comience la prueba gratuita y planifique',
          'askSomething': 'Pregunta algo',
          'premiumPrice1': 'INR 183.88/mes',
          'premiumPrice2': 'INR 399.00/semana',
          'premiumPrice3': 'INR 95.87/mes',
          'voiceIsOff': 'La voz está apagada',
          'offer1': '1 Mes',
          'offer2': '1 Semana',
          'offer3': '12 Mes',
          'imageGeneration': 'Generación de imágenes',
          'imageSize': 'Tamaño de la imagen',
          'imagePreview': 'Vista previa de la imagen',
          'share': 'Compartir',
          'save': 'Ahorrar',
          'dark': 'Oscuro',
          'voiceIsOn': 'Voz activada',
          'year': 'Año',
          'alreadyPremium': 'Ya eres Premium',
          'buyPremium': 'Comprar Premium',
          'termsIn': 'Términos',
          'privacyIn': 'Privacidad',
          'autoRenewable': 'Renovable automáticamente, cancela en cualquier momento',
          'popular': 'Popular',
          'bestValue': 'Mejor valor',
          'oneYearPlan': 'Iniciar plan de 1 año',
          'oneMonthPlan': 'Iniciar plan de 1 mes',
          'oneWeekPlan': 'Iniciar plan de 1 semana',
          'getOlaPurchase': 'Obtienes un artículo de compra antiguo',
          'notPurchaseBefore': 'No has comprado nada antes.',
          'purchaseDone': 'Compra realizada',
          'failedFetch': 'Recuperación fallida',
          'unlockFeature': "función de desbloqueo",
          'proVersion': 'Versión Pro',
          'removeAds': 'Desbloquee todas las funciones y elimine los anuncios.',
          'watchAds': 'Ver anuncios',
          'requests': 'ver un anuncio para desbloquear 1 solicitudes más',
          'shareText':
              '''Te comparto EduChat, una app educativa con Inteligencia Artificial, te ayuda en todo, descárgala aquí:
https://play.google.com/store/apps/details?id=com.educhat.chatai''',
        }
      };
}
